### ISSUE TITLE
Not php7.2 compatible

### ISSUE THREAD

**Issue by wranger** [robinpowered/php-ntlm#10]
Got the " Function mcrypt_encrypt() is deprecated" error message, same thing like using:

pecl install mcrypt-1.0.1

What a nightmare.

**Comment by Rican7** [comment]
Ooo, good point. Sorry about that @wranger.

The use of the `mcrypt` extension in this project has been deprecated as of #8 (for reference, also see #1 and #7).

Unfortunately, it looks like we forgot to deprecate, and provide an alternative, to the [Mcrypt](https://github.com/robinpowered/php-ntlm/blob/v0.4.0/src/Robin/Ntlm/Crypt/Des/McryptDesEncrypter.php) and [OpenSSL](https://github.com/robinpowered/php-ntlm/blob/v0.4.0/src/Robin/Ntlm/Crypt/Des/OpenSslDesEncrypter.php) versions of the `DesEncrypterInterface`... whoops!

We should definitely do that.

The `mcrypt` extension has been removed from core and into `PECL` as of PHP 7.2.0:
http://php.net/manual/en/migration72.other-changes.php#migration72.other-changes.mcrypt

**Comment by Rican7** [comment]
@wranger For the time being, you should be able to use the newly released `mcrypt-1.0.2` version on PECL, as its compatible with PHP 7.2.x: https://pecl.php.net/package/mcrypt

**Comment by Rican7** [comment]
I had a chat with @paragonie-scott [on Twitter](https://twitter.com/trevorsuarez/status/1085982005668458498) and he OK'd our use of `OpenSSL` for the `DesEncrypterInterface`.

So we can keep that, but we should likely still deprecate (and eventually remove) the `McryptDesEncrypter` implementation.

![2019-01-17_19-15-44](https://user-images.githubusercontent.com/742384/51361327-9b043a80-1a8c-11e9-9513-0716af8e4151.png)

**Comment by wranger** [comment]
Thanks for your reply. I need the NT and LM hashes for Radius WLAN Authentification (EAP) stored in an LDAP Directory.

I used the http://pear.php.net/package/Crypt_CHAP  module, no fix for that.

At the moment I use the linux shell:

 apt-cache search smbencrypt
freeradius-utils - FreeRADIUS client utilities
smbencrypt test
LM Hash                         NT Hash
--------------------------------        --------------------------------
01FC5A6BE7BC6929AAD3B435B51404EE        0CB6948805F797BF2A82807973B89537
